### ISSUE TITLE
10.5 "/" matches ""?

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#100]
## Location within the Book

* Chapter or Appendix: 10 Create Our First Django Template
* Section: 10.5 Recap
* Subsection:

## Description 

> • Since the index was requested, it matches the regular ex-
pression '/'
> • Therefore the matching URL pattern is:
> `path('', HomepageView.as_view(), name='home'),`

This section left me a bit confused since it says that `/` matched `""`. Perhaps it has to be changed? Or are leading `/`s stripped?

**Comment by rohithpr** [comment]
Probably a left over from when this change was made: https://github.com/roygreenfeld/django-crash-course/issues/8

**Comment by pydanny** [comment]
🚢 🧀
