### ISSUE TITLE
52 - error running code

### ISSUE THREAD

**Issue by jtalarovich** [roygreenfeld/django-crash-course#101]
I entered the code as written in the book for section 52.  When i ran the coverage test in 52.3.1 I got this error.

E       compressor.exceptions.UncompressableFileError: 'js/vendors.js' could not be found in the COMPRESS_ROOT '/Users/gn/dev/everycheese/staticfiles' or with staticfiles.

I ran collectstatic thinking it was that but that didn't fix it.

**Comment by jtalarovich** [comment]
I commented this out in the base.html and the test worked.
'''
<script src="{% static 'js/vendors.js' %}"></script>
'''

**Comment by pydanny** [comment]
We removed the `vendor.js` file from django-crash-starter

**Comment by pydanny** [comment]
:ship: :cheese:
