### ISSUE TITLE
Section 46.5: The class of the button has changed compared to 45.4 

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#102]
## Location within the Book

* Chapter or Appendix: 46
* Section: 5
* Subsection: end of code block

## Description 

In comparison to Chapter 45.4 the class for the button has changed.
It was:

```
<button type="submit" class="btn btn-primary">Save</button>
```

Now in chapter 46.5 it is:
```
<button type="submit" class="btn">Save</button>
```

This leads to a button without any color and no border. So, on a white background you actually don't see any button.

**Comment by pydanny** [comment]
🚢 🧀
