### ISSUE TITLE
13.2 Next Steps Grammar

### ISSUE THREAD

**Issue by kanusek** [roygreenfeld/django-crash-course#106]
* Chapter or Appendix: 13
* Section: 2
* Subsection: Next Steps

The word "project" following EveryCheese would improve this sentence.

> Now that we’ve finished the Hello, World in Django project, let’s move on to the EveryCheese on the next page.

To: 
> Now that we’ve finished the Hello, World in Django project, let’s move on to the EveryCheese project on the next page.

**Comment by pydanny** [comment]
Audrey just rewrote the whole chapter. 😄

**Comment by kanusek** [comment]
Awesome 😄

**Comment by pydanny** [comment]
You should have gotten the update by now. Check it out and let us know what you think! 😄
