### ISSUE TITLE
15.2 Formatting issue for repo URL

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#107]
## Location within the Book

* Chapter or Appendix: 15 Using Cookiecutter and Template
* Section: 15.2 Cookiecutter Project Templates
* Subsection:

## Description 

The URL in the text overflows the page borders and needs some attention. :)

<img width="652" alt="Screen Shot 2020-02-18 at 12 58 34 PM" src="https://user-images.githubusercontent.com/10276811/74713353-59f6d080-5220-11ea-8dc7-6fc0306d85e0.png">

**Comment by pydanny** [comment]
🚢 🧀
