### ISSUE TITLE
16.3 / 17.1 Duplicated content

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#110]
## Location within the Book

* Chapter or Appendix: 16 and 17
* Section: 16.3 and 17.1
* Subsection:

## Description 

The sections share the same title and the first two sentences. Only the third sentence varies between the two sections.

> ### 16.3 Let’s Run the Project
> The code in everycheese/ is a real Django project with tons of working features. You can actually run it, just like any other Django project.
> But first you’ll need to install your project’s dependencies.

> ### 17.1 Let’s Run the Project
> The code in everycheese/ is a real Django project with tons of working features. You can actually run it, just like any other Django project.
> Let’s make that happen!

**Comment by pydanny** [comment]
🧀 🚢
