### ISSUE TITLE
21.2 Images can be reorganized

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#111]
## Location within the Book

* Chapter or Appendix: 21
* Section: 21.2
* Subsection: Figures 12 and 13

## Description 

Figures `12 (Verification email in console window)` and `13 (Page with Confirm button)` belong with the section `21.2.1 Grab the Email Confirmation Link`. However, they appear under `21.3 Why Are Emails Printed in the Console?`

Reorganizing these figures would be great.

**Comment by pydanny** [comment]
These should be organized properly per issues filed previously. Can you confirm that they are in place to your satisfaction?

**Comment by rohithpr** [comment]
<img width="485" alt="Screen Shot 2020-02-23 at 12 05 18 AM" src="https://user-images.githubusercontent.com/10276811/75097388-2ca07e80-55a2-11ea-95ce-bf98b05fde16.png">

I expected `Figure 12` to be displayed before section `21.2.1 Grab the Email Confirmation Link`. Similarly, I expected `Figure 13` to be displayed before `21.3 Why Are Emails Printed in the Console?`.

That said, I'm not sure if this is an issue or if this is indeed how you intend to present it.

**Comment by pydanny** [comment]
Fixed. 🧀 🚢
