### ISSUE TITLE
16.2 Inconsistent usage of term django-crash-starter

### ISSUE THREAD

**Issue by kanusek** [roygreenfeld/django-crash-course#112]
* Chapter or Appendix: 16
* Section: 2
* Subsection:

At the beginning of the paragraph the cookiecutter we’re using is called:

> crash-django-starter

Instead of:
> django-crash-starter

In the second paragraph its referenced as:
> crash-course-django-starter

**Comment by pydanny** [comment]
Oops.

🚢 🧀
