### ISSUE TITLE
Section 49.2: Typo Usermoder -> Usermodel

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#113]
## Location within the Book

* Chapter or Appendix: 49
* Section: 2
* Subsection: Paragraph before the second set of bullet points

## Description 

> Book: "Powered by ```creator``` foreign key to the **Usermoder**, ...

> Proposal: "Powered by ```creator``` foreign key to the Usermodel, ...

**Comment by pydanny** [comment]
🚢 🧀
