### ISSUE TITLE
Section 51: Old test code in this paragraph

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#115]
## Location within the Book

* Chapter or Appendix: 51
* Section: -
* Subsection: code block

## Description 

The test in this section is old. It has been replaced in previous chapter by this code in order to have a generic ```name```:

```
def test___str__():
    cheese = CheeseFactory()
    assert cheese.__str__() == cheese.name
```

**Comment by pydanny** [comment]
🚢 🧀
