### ISSUE TITLE
Section 52.3: Zen of Python: Explicit is better than implicit

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#117]
## Location within the Book

* Chapter or Appendix: 52
* Section: 3
* Subsection:

## Description 

> Book: "**All we'll do** at first is check that the views are returning valid 200 HTTP status codes for ```GET``` requests.

It is specifically stated that we are testing for status code 200, but what is actually done in the test for the Cheese List and the Cheese Detail is to test if certain strings are existing in the html-response. Granted, you would probably not get the expected string responses if the status code would not be 200, but isn't that little bit too implicit ?!?!

**Comment by pydanny** [comment]
While not obvious, the `assertContains` function tests if Django is returning a 200 status code. See https://docs.djangoproject.com/en/3.0/topics/testing/tools/#django.test.SimpleTestCase.assertContains

We're adding a text box to make it more obvious.

**Comment by SmartC2016** [comment]
Thanks for the explanation. I've checked the docs and yes ```status_code``` is a paramter for ```assertContains()```and has a default value of ```200```. That I didn't expect. :)

**Comment by pydanny** [comment]
Indeed, it should be called `assertContainsAndCheckStatus`. 😆
