### ISSUE TITLE
Section 52.8: Typo in second to last paragraph

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#118]
## Location within the Book

* Chapter or Appendix: 52
* Section: 8
* Subsection: second to last paragraph

## Description 

In the book it says:

> „In fact, it’s not uncommon for experienced **code** to come back to tests they wrote years, months, weeks, or even days earlier and find ways they could make them better.“

Should code actually be **developers**? Or coders?

**Comment by pydanny** [comment]
🧀 🚢
