### ISSUE TITLE
21.11 My Info URL

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#119]
## Location within the Book

* Chapter or Appendix: 21
* Section: 21.11 What About the Code?
* Subsection:

## Description 

> The My Info button points to a URL named update within the users namespace, which is wired up with UserUpdateView. You saw that earlier.

I couldn't find a reference to `users/urls.py` earlier in the book.

**Comment by pydanny** [comment]
🚢 🧀
