### ISSUE TITLE
Reference to video which I don't think features in the course.

### ISSUE THREAD

**Issue by magnusvaughan** [roygreenfeld/django-crash-course#120]
## Location within the Book

* Chapter or Appendix: 39
* Section: 39.0

## Description 

> The following passage mentions a video, which I don't think is part of the new course, but may be part of the old training materials:

> Note: we’ve made some changes to CheeseFactory that aren’t
> in the video yet. The concepts in the video still apply, but the
> fields differ slightly. We’ll update the video shortly to match.

**Comment by pydanny** [comment]
🚢 🧀
