### ISSUE TITLE
39.5 - Typo -  "It is our understanding that tn English"

### ISSUE THREAD

**Issue by magnusvaughan** [roygreenfeld/django-crash-course#121]
## Location within the Book

* Chapter or Appendix: 39
* Section: 39.5
* Subsection:

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

>Line "It is our understanding that tn English...." should be "It is our understanding that in English"

**Comment by pydanny** [comment]
🚢 🧀
