### ISSUE TITLE
11.3 - Code Sample and Explanation mismatch

### ISSUE THREAD

**Issue by chumaumenze** [roygreenfeld/django-crash-course#125]
## Location within the Book

* Chapter: *11 Working With Variables in Templates*
* Section: *11.3 Extend HomepageView*
* Subsection: N/A

## Description 

```
def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs) 
    context['my_statement'] = 'Nice to see you!'
    return context
```
Explanation to the above code suggests `context['my_statement'] = 'Hello'`.

**Comment by SmartC2016** [comment]
Hi chumaumenze, you seem to have an old version of the book. That part was already fixed.

This is a duplicate to issue #43 .

**Comment by pydanny** [comment]
Thanks for the submission @chumaumenze and the catch @SmartC2016!
