### ISSUE TITLE
Section 55.1: Test code is different than first introduced in 52.3.2

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#127]
## Location within the Book

* Chapter or Appendix: 55
* Section: 1
* Subsection: the to be refactored test function

## Description 

The test which is to be refactored is different as in the first time that it was introduced.

In section 52.3.2 the ```test_good_cheese_detail``` was introduced. There the function had two input arguments ```(rf, admin_user)```. The ```
admin_user```was not really explained.

Now in section 55.1 the code which is to be refactored, is different from 52.3.2. The ```
admin_user``` is missing here.

**Comment by pydanny** [comment]
🧀 🚢
