### ISSUE TITLE
Section 56: This is the end my friend ?!

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#128]
## Location within the Book

* Chapter or Appendix: 56
* Section: --
* Subsection: --

## Description 

Horay, I managed to finish the book today. It was a lot of fun and I learned a lot ... thank you very much!

However, flipping the page after chapter 55.5 I saw chapter 56 and this was not what I was expecting.

I'm missing a summary of what we have achieved so far, outlook what nice features could or even will be added, specifically which parts will come in the future (as I have understood there will be more things to come) ...

This is a very sudden ending ...

**Comment by pydanny** [comment]
👍 

Thanks for this one. We'll revise the ending to be better. ❤️

**Comment by pydanny** [comment]
As always, @SmartC2016, thank you for your feedback. When you get a chance, can you email me at daniel.roy.greenfeld AATT roygreenfeld DOTTY com?
