### ISSUE TITLE
22.4 Duplicate paragraphs

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#129]
## Location within the Book

* Chapter or Appendix: 22
* Section: 22.4 Try It Out
* Subsection:

## Description 

The following paragraphs are duplicates, with some minor changes between them:

> As we can see, now users can add and edit their bios. But the bios still don’t show up on user profiles. We’ll notice that UserDetailView still looks like this:

> As you can see, now users can add and edit their bios. But the bios field still doesn’t show up on user profiles. You’ll notice that UserDetailView still looks like this:

<img width="492" alt="Screen Shot 2020-02-21 at 12 34 19 PM" src="https://user-images.githubusercontent.com/10276811/75011807-6d03dd80-5478-11ea-9e55-577a4647036a.png">

---

Also, the screenshot shows up in the next page, and not immediately after "looks like this:". But I'm guessing that you're already aware of this issue of images not rendering where they should as I saw a related discussion somewhere.

**Comment by pydanny** [comment]
🚢 🧀
