### ISSUE TITLE
What is the naming convention for objects in a template?

### ISSUE THREAD

**Issue by pors** [roygreenfeld/django-crash-course#130]
##  Location within the Book

* Chapter: 35.2 Fill in the Template

## Description 

In the `cheese_list.html` template apparently the variable `cheese_list` is available. I tried to play with the naming of classes and "mapping" that on this variable name, but I don't get where the name `cheese_list` comes from. In the [documentation](https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-display/#listview), `object_list` is used in the example:

    {% for article in object_list %}

What magic is happening and how do I know what variable name is available in the template?
I'm probably not the only django-newbie who doesn't get this, so maybe something to mention in the book?

**Comment by quique** [comment]
The magic is revealed in the [documentation](https://docs.djangoproject.com/en/3.0/ref/class-based-views/mixins-multiple-object/#django.views.generic.list.MultipleObjectMixin.get_context_object_name), but I agree it should be explained in the book.

**Comment by pors** [comment]
@quique thanks for the reply. It makes sense that it uses the underlying model name although I am a proponent of "Explicit is better than implicit".

The example [here](https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-display/#listview) seems to be wrong then? The model is named `Article`, but the variable that is available in the template is named `object_list`.

**Comment by quique** [comment]
> The example [here](https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-display/#listview) seems to be wrong then? The model is named `Article`, but the variable that is available in the template is named `object_list`

Django documentation is terse, but not wrong.

The list of objects that `ListView` will display is always called `object_list`.

Besides, it will have another name. By default, `<model_name>_list`. This second name is configurable via `context_object_name` (or `get_context_object_name()`). Whatever its name, is has the same value as `object_list`.

HTH

**Comment by pors** [comment]
Cool, thanks for clarifying that! I thought I tried `object_list` as well in `cheese_list.html` and it didn't work. Anyways, I know how it works now, thanks :)

**Comment by pydanny** [comment]
Lovely dialogue! We added an explanation into that section for the source of `cheese_list`.  😄 

🧀 🚢
