### ISSUE TITLE
34.3: Grammar error?

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#133]
## Location within the Book

* Chapter or Appendix:
* Section: 34.3 See the View in Action
* Subsection:

## Description 

> 2. The remainder of the URL was **be** a match for `''`, so `CheeseListView.as_view()` was called.

I think this sentence is not grammatically correct. I guess that _be_ should be removed.

**Comment by pydanny** [comment]
🚢 🧀
