### ISSUE TITLE
27. Explain Django 3-style enums, choices, get_foo_display()

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#134]
## Location within the Book

* Chapter or Appendix: 27
* Section:
* Subsection: 26.6.4 Add Firmness Field, 37.1 Add a Cheese Detail Template

## Description 

In 27.6.4, the firmness field is defined using enum-powered TextChoices.
In 38.1, the template uses `get_firmness_display` to show the cheese's firmness attribute.

But it's never explained how all this actually works.

**Comment by pydanny** [comment]
👍

**Comment by pydanny** [comment]
🚢 🧀
