### ISSUE TITLE
41.5: Properly use firmness

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#136]
## Location within the Book

* Chapter or Appendix:
* Section: 41.5 Replacing the Direct Cheese Model Call in Our Existing Test
* Subsection:

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> Then change this part where we created a cheese via `create()`:
> ```
> cheese = Cheese.objects.create(
>     name="Stracchino",
>     description="Semi-sweet cheese that goes well with starches.",
>     firmness=Cheese.Firmness.soft,
> )
> ```

If I'm not mistaken, `Cheese.Firmness.soft` should actually be `Cheese.Firmness.SOFT`.

**Comment by pydanny** [comment]
🚢 🧀
