### ISSUE TITLE
41.2: Use f-strings instead of format()

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#137]
## Location within the Book

* Chapter or Appendix:
* Section: 41.2 Bulk Generation
* Subsection:

## Description 

```
... CheeseFactory(name="Sample Cheese {}".format(x))
```

Perhaps a pet peeve of mine, but, as this books is undertitled _Covers Python 3.8_, wouldn't it be preferable to write this code like this?
```
... CheeseFactory(name=f"Sample Cheese {x}")
```

**Comment by pydanny** [comment]
This is so embarrassing! 😭

**Comment by pydanny** [comment]
🚢 🧀

**Comment by pydanny** [comment]
Thanks for the wonderful catch! 😸
