### ISSUE TITLE
41.7: Inaccurate commit message

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#138]
## Location within the Book

* Chapter or Appendix:
* Section: 41.7 Commit Our Work
* Subsection:

## Description 

```
git commit -m "Create a CheeseFactory and use it in Cheese model test"
```

The CheeseFactory was already created and committed in section 39.5 Commit the Changes.
Here we are just using it in the test.

**Comment by pydanny** [comment]
🚢 🧀
