### ISSUE TITLE
A few issues I spotted

### ISSUE THREAD

**Issue by adamchainz** [roygreenfeld/django-crash-course#14]
## Location within the Book

"Conventions used in this book": Clicking the "github.com/roygreenfeld/django-crash-course" link included a "5" at the end of the URL, a 404: github.com/roygreenfeld/django-crash-course5

3.2: "#!/Usr/Bin/Env Python" should not be capitalized

3.4: "MIDDLEWARE_CLASSES" is completely removed by Django 3.0, perhaps use a different example setting like SECRET_KEY

5.2: Perhaps mention storing password securely as you do later in the book?

6.4: Missing screenshot

10.2: Perhaps mention this is incomplete HTML, as I recently added to the Django tutorial: https://github.com/django/django/pull/12316

14.1: "The Ultimate Django Setup{ultimate-django- setup}."

19: Repeat mentions of GitLab instead of GitHub

20: I can't figure out what the "stinky cheeses" are an analogy for

28.3: "Str" is capitalized in the title

28.3: This is the first mention of PEP 8 and not violating it in the book. Perhaps better to leave it out?

28.3: Maybe test with str() rather than __str__ ?

30.7.1: typo amaz1ing

30.7.1: "Don’t Use list_editable" seems a bit out of place, we haven't learnt anything about configuring the Django admin, and you're warning against one of its many footgun features? Perhaps better as an admonition in the documentation, which currently doesn't document that race condition possibility at all: https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_editable

32.1: Technically a @require_GET would be needed on the FBV to be equivalent. Also I think the *args, **kwargs is unnecessary on both CBV and FBV approaches and just risks students developing copy-paste practice of adding that to every view.

32.4: ccbv.co.uk link includes a 41 at the end so is a 404 when clicked

34.1: probably better to use a list for urlpatterns to avoid missing-comma tuple confusion?

43.3: It's "Chris Beaven" not "Beavens".

43.5: PyPI is nice now, maybe describe typing it in the box at https://pypi.org/ instead?

43.6.1: The term "hard fork" isn't really well described here?

47.6: I think a better mixin example would use super()

48.2: You don't want to use a data migration to fill in cheesehead? After the backfill, the column remains nullable so the data integrity isn't perfect.

**Comment by pydanny** [comment]
We've address most of this, which will show up in the changelog. Thanks!

🚢 🧀
