### ISSUE TITLE
28.3 Why __str__() instead of str()?

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#140]
## Location within the Book

* Chapter or Appendix: 28
* Section: 28.3 Let’s Test the `__str__()` Method.
* Subsection:

## Description 

I'm curious to know why we're testing `cheese.__str__()` instead of `str(cheese)`. We shouldn't be calling `__str__` directly in prod code, why are we making an exception in test code?

**Comment by pydanny** [comment]
Because we're doing an explicit test of the `__str__()` method instead of the `str()` built-in function.

That said, there's room for both. Now the test asserts the following:

```
assert cheese.__str__() == "Stracchino"
assert str(cheese) == "Stracchino"
```
