### ISSUE TITLE
9.4 Typo - 'affiliate' -> 'associate'

### ISSUE THREAD

**Issue by tobyontour** [roygreenfeld/django-crash-course#142]
Section 9.4 Terminology: “Wire in the URL”

>> When we say “Wire in the URL”, that means to affiliate the Django view we just
wrote with a web location on our site.

Should be 'associate' I believe.

**Comment by pydanny** [comment]
Thanks for the catch @tobyontour. You will show up in our next update in the acknowledgements section!

🚢 :cheese
