### ISSUE TITLE
49.2 Missing 'avatar_tags' library 

### ISSUE THREAD

**Issue by DROMZEE** [roygreenfeld/django-crash-course#143]
* Chapter or Appendix: 49
* Section: 49.2 Display the Creator on the Cheese Detail Pages
* Subsection:

## Description 

> django.template.exceptions.TemplateSyntaxError: 'avatar_tags' is not a registered tag library

![Annotation 2020-02-26 235320](https://user-images.githubusercontent.com/12269933/75395687-32c09300-58f3-11ea-907b-84549f61a49b.png)

## Solution
```
pip install django-avatar
```
* source: https://django-avatar.readthedocs.io/en/latest/

Proposal : we could add it to requirements ?

**Comment by pydanny** [comment]
This was fixed some time ago. Are you receiving updates to the book? If not, please email us so we can make certain you are working with the current edition of the book.
