### ISSUE TITLE
Section 47.3.1 - Adjust placement of Figure 54

### ISSUE THREAD

**Issue by mattwinslow** [roygreenfeld/django-crash-course#144]
## Location within the Book

* Chapter: 47
* Section: 3
* Subsection: 1

## Description 
The text currently reads:
> In our private (incognito) browser window, let’s reload the Add Cheese form (http://127.0.0.1:8000/cheeses/add/).
> We should now see this:
> What happened?

It seems as though Figure 54 should be inserted between the lines "We should now see this:" and "What happened?" as illustrated below:
> We should now see this:
> {{ FIGURE 54 }}
> What happened?

Screenshot below for quick reference:
<img width="425" alt="Screen Shot 2020-02-26 at 11 11 39 PM" src="https://user-images.githubusercontent.com/202878/75411494-6d273180-58ed-11ea-9dd8-3d39d237de6b.png">

**Comment by pydanny** [comment]
Beautiful issue! Yuo've been given credit, which will show up in the next release.

🚢 🧀
