### ISSUE TITLE
43.5 Swap order of PyPI URL and Project

### ISSUE THREAD

**Issue by mattwinslow** [roygreenfeld/django-crash-course#145]
## Location within the Book

* Chapter: 43
* Section: 5
* Subsection: N/A

## Description 

> We prefix **https://pypi.org/project/** with the name of the project
and check it in our browser thus: `https://pypi.org/project/django-countries`

Minor nitpick, but perhaps the phrasing of this sentence should be adjusted?
> We prefix the name of the project with **https://pypi.org/project/**
and check it in our browser thus: `https://pypi.org/project/django-countries`

Alternatively, this could be rewritten as:
> We append the name of the project to **https://pypi.org/project/**
and check it in our browser thus: `https://pypi.org/project/django-countries`

**Comment by pydanny** [comment]
Great point! Love the clarity!

🚢 🧀
