### ISSUE TITLE
34.3 Update tense

### ISSUE THREAD

**Issue by mattwinslow** [roygreenfeld/django-crash-course#146]
## Location within the Book

* Chapter: 34
* Section: 3
* Subsection: N/A

## Description 

> 1. Django’s URL dispatcher found match for 'cheeses/' and
**send** the rest of the URL to everycheese.cheeses.urls.

Change **send** to **sent** to match the tense used in the rest of the sentence.

**Comment by pydanny** [comment]
🚢 🧀
