### ISSUE TITLE
44.4 Missing word in last sentence?

### ISSUE THREAD

**Issue by mattwinslow** [roygreenfeld/django-crash-course#147]
## Location within the Book

* Chapter: 44
* Section: 4
* Subsection: N/A

## Description 

> In future Django Crash Course extensions we’ll go over even more testing tricks that can be with
fakes.

Perhaps add the word **used** to the sentence:
> In future Django Crash Course extensions we’ll go over even more testing tricks that can be **used** with fakes.

**Comment by pydanny** [comment]
🚢 🧀
