### ISSUE TITLE
Warning about password manager

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#148]
## Location within the Book

* Chapter or Appendix: All instances of the warning about creation and storage of passwords.
* Section:
* Subsection:

## Description 

> It’s bad practice to use simplistic **names**, even for local development.

Should it be "simplistic passwords" instead of "simplistic names"?

Full text:

> Copy this password into a password manager!
It’s bad practice to use simplistic names, even for local de- velopment. We want to promote strong security habits and this is one of them. Also, don’t stick passwords into plain- text or spreadsheet files. Instead, lean on secure password managers like 1Password or open source options.

**Comment by pydanny** [comment]
🚢 🧀
