### ISSUE TITLE
Missing space Beta version p.264

### ISSUE THREAD

**Issue by jonndoe** [roygreenfeld/django-crash-course#149]
## Location within the Book

* Chapter or Appendix:  55
* Section:  3
* Subsection: n/a
## Description 

> ........test case in test_views.py, comment it extensively. and call
ittest_good_cheese_update_view().
^missing  space in ittest.

**Comment by pydanny** [comment]
🚢 🧀 

We'll add you to the acknowledgements chapter in the next release!

**Comment by pydanny** [comment]
@jonndoe Can you provide the name you want to be listed as in the acknowledgements?

**Comment by jonndoe** [comment]
Yes, of course, name is Lukichev Vasily.04.03.2020, 21:32, "Daniel Roy Greenfeld" <notifications@github.com>:@jonndoe Can you provide the name you want to be listed as in the acknowledgements?

**Comment by jonndoe** [comment]
Thanks for your book , was really interesting for me to read!04.03.2020, 21:31, "Daniel Roy Greenfeld" <notifications@github.com>:🚢 🧀
We'll add you to the acknowledgements chapter in the next release!
