### ISSUE TITLE
Command line tutorial - TODO

### ISSUE THREAD

**Issue by chumaumenze** [roygreenfeld/django-crash-course#15]
## Location within the Book
 
* Chapter: **The Ultimate Django Setup**
* Section: **Goal: A Professional-Quality Development Environment**
* Subsection: N/A
 
## Description 

There's a TODO  that hasn't been implemented yet. 

> Make sure you:
>     - Are comfortable using the command line. If not, work through a command line tutorial such as *TODO*.

**Comment by pydanny** [comment]
Thanks for letting us know about the TODO. 

In the future, please follow the guidelines provided in the `ISSUE_TEMPLATE`, specifically the instructions about **page numbers**.

**Comment by chumaumenze** [comment]
Noted & updated. 

I noticed more TODOs in the book. Would it help if I create an issue for every one of them?
