### ISSUE TITLE
44.6: Use the latest version of django-countries

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#151]
## Location within the Book

* Chapter or Appendix: 44
* Section: 6 Install It
* Subsection:

## Description 

> As usual, add the package and its version number to `requirements/base.txt`:
>
> `django-countries==5.5`

Please notice that django-countries 6.0 has been released.

**Comment by pydanny** [comment]
@luzfcb This might have corrected issues identified elsewhere with django-countries.

**Comment by pydanny** [comment]
Yup, fixes those problems.

**Comment by pydanny** [comment]
🚢 🧀

**Comment by pydanny** [comment]
This was corrected 9 days ago. Closing it.
