### ISSUE TITLE
43.7.1 THIRD_PARTY_APPS is a list, not a tuple

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#153]
## Location within the Book

* Chapter or Appendix:
* Section:
* Subsection: 43.7.1 Installation

## Description 

```
THIRD_PARTY_APPS = (
    ...
    "django_countries", # CountryField
)
```

In `django-crash-starter`, `THIRD_PARTY_APPS` is a list, not a tuple.

**Comment by pydanny** [comment]
🧀 🚢
