### ISSUE TITLE
48.1: Explain foreign keys

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#156]
## Location within the Book

* Chapter or Appendix:
* Section: 48.1 Add a Creator Field
* Subsection:

## Description 

> ```
> creator = models.ForeignKey(
>     settings.AUTH_USER_MODEL,
>     null=True,
>     on_delete=models.SET_NULL
> )
> ```
> 
> This field is a simple ForeignKey to a User object.

A brief explanation of foreign keys and the `on_delete` clause should be added.
Or, at least, a link to Django's documentation: <https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.ForeignKey>

**Comment by pydanny** [comment]
🚢 🧀
