### ISSUE TITLE
34.1: Explain app_name

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#157]
## Location within the Book

* Chapter or Appendix:
* Section: 34.1 Define Cheese URL Patterns
* Subsection:

## Description 

> In our cheeses app, create a new file called `urls.py.`  Open it in our text editor and add the following code:
> 
> ```
> # everycheese/cheeses/urls.py
> from django.urls import path
> from . import views
> 
> app_name = "cheeses"
> urlpatterns = [
>     path(
>         route='',
>         view=views.CheeseListView.as_view(),
>         name='list'
>     ),
> ]
> ```

`app_name` is not explained.

Then, on section 45.2 Add the Corresponding URL Pattern, `app_name` is absent.

**Comment by pydanny** [comment]
🚢 🧀
