### ISSUE TITLE
51: Presented code is not what we have

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#159]
## Location within the Book

* Chapter or Appendix: 51 Update the Cheese Model Tests
* Section:
* Subsection:

## Description 

> Open cheeses/tests/test_models.py in our text editor. We should have one test in there:
> 
> ```
> def test__str__():
>     cheese = CheeseFactory(name="Stracchino")
>     assert cheese.__str__() == cheese.name
> ```

We removed `name="Stracchino"` in section  
41.6 Removing the Name Entirely
so our current test is:

```
def test___str__():
    cheese = CheeseFactory()
    assert cheese.__str__() == cheese.name
```

**Comment by pydanny** [comment]
Thank you! ❤️ 

🚢 🧀
