### ISSUE TITLE
#ultimate-django-setup link not found

### ISSUE THREAD

**Issue by chumaumenze** [roygreenfeld/django-crash-course#16]
## Location within the Book

* Chapter: **1 What Does Hello, World Mean?** 

* Section: **1.4 Prerequisites** 

* Subsection: N/A

## Description 

Link to Ultimate Django Setup not found. Epub reader error: `"#ultimate-django-setup" not found`

> ... If you don’t have it ready, go to the **Ultimate Django Setup chapter**.

**Comment by pydanny** [comment]
Thanks for the catch! Removing it for next release and attribution will be given!

🚢 🧀
