### ISSUE TITLE
53.1: Markdown error

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#163]
## Location within the Book

* Chapter or Appendix:
* Section: 53.1 Add the Imported Cheese
* Subsection:

## Description 

> Create the module `cheeses/tests/test_urls.py`. Import `reverse` and
> `resolve` from ‘django.urls, which we’ll need to test URL patterns

‘django.urls => `django.urls`

**Comment by pydanny** [comment]
🚢 🧀
