### ISSUE TITLE
54.4.1: Title is not changed

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#165]
## Location within the Book

* Chapter or Appendix:
* Section:
* Subsection: 54.4.1 Smart Titling

## Description 

This section makes the header (&lt;h1&gt; tag) flexible enough to handle both `CheeseCreateView` and `CheeseUpdateView` views. 

However, the title of the page (&lt;title&gt; tag) is not changed.

I think this could be a good opportunity to introduce the `with` template tag.

**Comment by pydanny** [comment]
Great suggestion! However, making string assignments with the `with` template tag is a bit klutzy.  It's better for complex values.

For now, we'll call  `request.resolver_match.url_name`  instead.  Maybe later we'll add in call to a `view.action` variable.

**Comment by pydanny** [comment]
I got the `{% with %}` template tag in. Thanks for the suggestion @quique!
