### ISSUE TITLE
Conda on the Mac

### ISSUE THREAD

**Issue by diederikdevries** [roygreenfeld/django-crash-course#166]
As requested by you :)

Hi Roy!

Thanks for the alpha version! As a Mac-user, I already ran into problems with installing Conda.

I installed it first with the pkg-method, but that didn’t work out. Then I used the bash-installation method, which did work, but borked on having zsh.

The key was at https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html.

Use (in my case) source /Users/diederik/miniconda3/bin/activate, then Conda init zsh. Works like a charm :)

**Comment by pydanny** [comment]
Oops, this got added into the book a long time ago. Your name is already in the credits. 😄 

🚢 🧀
