### ISSUE TITLE
Move PostgreSQL troubleshooting instructions to an appendix?

### ISSUE THREAD

**Issue by audreyr** [roygreenfeld/django-crash-course#169]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile.

## Location within the Book
17.5.1 and .2

* Chapter or Appendix: 17
* Section: 5
* Subsection: 1 and 2

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

Readers may accidentally type in the troubleshooting instructions even if `createdb` worked just fine. Let's move them to an appendix. Similarly, let's consider following this pattern in other places in the book.

**Comment by pydanny** [comment]
❤️ 🍼  🚢 🧀
