### ISSUE TITLE
Missing image: unvalidated/django-admin.png not found

### ISSUE THREAD

**Issue by chumaumenze** [roygreenfeld/django-crash-course#17]
## Location within the Book 

* Chapter: **6 Practice Using the Admin**

* Section: **6.4 Explore the Admin**

* Subsection: N/A

## Description

Missing image. Epub reader error: `unvalidated/django-admin.png not found`

> ...the Authentication and Authorization tools:
>
>    **Django Admin**

**Comment by pydanny** [comment]
Thanks for catching this!

🚢 🧀
