### ISSUE TITLE
25.6 Suggested reorder of text

### ISSUE THREAD

**Issue by bfmcneill** [roygreenfeld/django-crash-course#171]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Chapter or Appendix: 25
* Section: 6

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> If grammar, enter problematic text here, otherwise delete this line.
It looks like "Now that we’ve seen how tests are constructed, let’s write some
more." was repeated

## Possible Solution
delete one of them, perhaps move "But how do we know where to begin writing tests?" above the tip
![issue](https://user-images.githubusercontent.com/16538715/75955038-57c48100-5e72-11ea-9e91-07c1371b16d3.PNG)

**Comment by pydanny** [comment]
Followed your suggestion precisely @bfmcneill!

🚢 🧀
