### ISSUE TITLE
15.3.2 README.md bad character

### ISSUE THREAD

**Issue by leighmforrest** [roygreenfeld/django-crash-course#173]
## Chapter 15 Section 3 part 2

When the `cookiecutter gh:roygreenfeld/django-crash-starter` command is run, this error comes up

`jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 22
  File "./README.md", line 1
    {{cookiecutter.project\_name}} `

**Comment by luzfcb** [comment]
@leighmforrest Thank you for reporting this issue.

This issue appears to have been fixed a few hours ago on https://github.com/roygreenfeld/django-crash-starter/pull/14

Could you please try to run the command again and let me know if it worked or not?

if it didn't work can you tell me which Operating System you are using?

**Comment by leighmforrest** [comment]
@luzfcb It works now. Thanks.
