### ISSUE TITLE
53.2: Explain assertions

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#177]
## Location within the Book

* Chapter or Appendix:
* Section: 53.2 Start With Imports
* Subsection:

## Description 

`assertContains` and `assertRedirects` are imported, but never explained.

## Possible Solutions

Explain that, in addition to Python's `assert` statement, Django's `TestCase` provide us many additional useful assertion methods such as `assertRaises()`, `assertCountEqual()`, `assertJSONEqual()`, etc.

**Comment by pydanny** [comment]
Removed `assertRedirects` 

`assertContains` is already done in the book.

**Comment by pydanny** [comment]
🚢 :cheese
