### ISSUE TITLE
Title doesn't pass test

### ISSUE THREAD

**Issue by leighmforrest** [roygreenfeld/django-crash-course#178]
## 55.2 
I've changed the template to display 'Add' dynamically in the title and in the header. 'Add' does show up when I manually visit the page. But when I run the tests, it fails.

Here is the function that is failing:

    def test_cheese_create_correct_title(rf, admin_user):
         """Page title for CheeseCreateView should be Add Cheese"""
          request = rf.get(reverse('cheeses:add'))
          request.user = admin_user
          response = CheeseCreateView.as_view()(request)
          assertContains(response, 'Add Cheese')

Here is the part of the template that is throwing the assertion failure:
`{% block title %}{{ request.resolver_match.url_name|title }} Cheese{% endblock %}`

If template goes back to original, it passes.
`{% block title %}Add Cheese{% endblock %}`

**Comment by pydanny** [comment]
🚢 🧀

**Comment by pydanny** [comment]
You've been given attribution in the update of the book going out right now! 😄
