### ISSUE TITLE
sendowl.com Access Denied

### ISSUE THREAD

**Issue by leighmforrest** [roygreenfeld/django-crash-course#179]
## Sendowl Access Denied

On March 6, 2020 I get an email saying that the book has been updated. I used the link in the email, and it said this:
`<div class="header">Item no longer available</div>
<div class="content">
<div class="explanation">
The merchant has deleted the item you are attempting to buy. We recommend you contact the merchant directly to find out if it is still possible to obtain the item.</div>
 </div>`

The same message appeared when I tried to access it with the original link.

**Comment by pydanny** [comment]
Fixed as of last night. Please try again!
