### ISSUE TITLE
Code example overflow

### ISSUE THREAD

**Issue by mpachas** [roygreenfeld/django-crash-course#180]
## Location within the Book

* Chapter or Appendix: 3 and more..
* Section: 3.3
* Subsection:

The "Collecting django: downloading" output is longer than the terminal box. Not sure if a pure 70 columns terminal can be copied in that box so everything gets easier. There are many of them:

3.3 Installation output
9.3.2 flavours dict
10.1 urls.py comment
18.3 createdb error when postgresql not running
18.4.1 Databases setting
20.4.2 git commit
22.3 Email backend when using env()
28.3 Description of cheese instance
40.2 CheeseFactory class description
42.5 Coverage output (last code block which has no background)
44.1.1 country_of_origin
44.1.2 country of origin
44.7.2 country_of_origin
47.7 git commit -m
49.3 git commit -m
51.4 import CheeseFactory
51.7 git commit -m
55.4.1 submit </button> tag
55.4.2 second box of block title

**Comment by pydanny** [comment]
We're working on line length issues this week. 😄

**Comment by pydanny** [comment]
🚢 🧀

**Comment by pydanny** [comment]
Credit goes to @luzfcb for his work on the backend code for the book to resolve this issue. 💥
