### ISSUE TITLE
Command line output not formatted as code box

### ISSUE THREAD

**Issue by mpachas** [roygreenfeld/django-crash-course#181]
* Chapter or Appendix: 42
* Section: 42.5
* Subsection:
The last paragraph of this section is coverage run output and it should look like all the other code boxes, with the darker background in the pdf. Font is ok. (It is also > 70 columns)

**Comment by pydanny** [comment]
While you reference the PDF, it's not clear if this problem in the epub or the pdf. Could you let us know which format this error is occuring?

**Comment by mpachas** [comment]
It is wrong in both. In the pdf it looks like a code box but in the epub pics (Google Play Books, Apple Books) you'll see that it is something strange.

Pdf
![nobackground425](https://user-images.githubusercontent.com/1219989/76299669-c7e06600-62bb-11ea-9049-2b5e6da3fc28.png)


it should look like this
![shouldbe425](https://user-images.githubusercontent.com/1219989/76299693-d2026480-62bb-11ea-9148-e36f1d2d259c.png)

Epub pictures
![20200310_103720](https://user-images.githubusercontent.com/1219989/76299792-f6f6d780-62bb-11ea-9966-fa545b8fc4d4.jpg)
![20200310_103828](https://user-images.githubusercontent.com/1219989/76299799-f9f1c800-62bb-11ea-8ce9-7b1e750630cb.jpg)

**Comment by mpachas** [comment]
It is formatted using <pre><code> html tags instead of your <div class="sourceCode" id="cb9"><pre class="sourceCode bash"><code class="sourceCode bash">

**Comment by pydanny** [comment]
Oh, that's a really good catch!

🚢 🧀 

BTW, again what's the name you want for receiving credit in the book?

**Comment by mpachas** [comment]
🍰  I'm Miguel Pachas

**Comment by pydanny** [comment]
Thanks @mpachas!
