### ISSUE TITLE
Code font in epub is tiny

### ISSUE THREAD

**Issue by mpachas** [roygreenfeld/django-crash-course#182]
I'm sure this is not unknown but I couldn't find an issue related 

MoonReader for Android
Google Books for ipad
Google Books for android

**Comment by pydanny** [comment]
Alas, supporting epub is hard, especially with Django and it's long, long object names. We have several  choices on how to resolve it:

1. Increase font size, diminish the line length of code examples, mashing everything together on more lines.
2. Increase font size, let code examples overflow
3. Take screen captures of the code examples, making copy/paste impossible
4. Leave it as it is

Any preferences?

**Comment by mpachas** [comment]
Will try some css changes this week. 
1,2 -> epub code font size looks different in several epub readers but might be increased a bit. Some variables, git commit messages, comments could be rewritten to adapt lines up to 65~70 chars so a lot of edge cases get fixed

There are some free commercial use monospace condensed fonts like Latin Modern Mono MMonotCond10-Regular (https://www.1001fonts.com/latin-modern-mono-font.html) that could help us to get more chars but keeping readability

4 is better than 3, I guess.

**Comment by JestersGhost** [comment]
In iBooks you cannot zoom in on the page to make the code larger. Increasing the text size in iBooks will not increase the size of the code

If you have an android device, you can zoom in the page and view the code in Google Play books.

Hope this is useful.

**Comment by pydanny** [comment]
Looking at integrating Latin Modern Mono MMonotCond10-Regular now

**Comment by pydanny** [comment]
After a LOT of manual testing, I got it working pretty well. Kudos to @luzfcb for adding Latin fonts to our growing book generation system. I would share a screen capture but my laptop is acting up.

**Comment by pydanny** [comment]
🚢 🧀

**Comment by pydanny** [comment]
![E13285BC-2FAA-46EA-BEB3-430B764FDE80](https://user-images.githubusercontent.com/62857/76875942-76d9f000-682e-11ea-97e4-cb30f66f62c1.jpg)
