### ISSUE TITLE
Dynamic Title test fails factory test

### ISSUE THREAD

**Issue by kevin-j-murray** [roygreenfeld/django-crash-course#184]
## Greetings! 

Many thanks for the book.  Had a problem similar to #178 but taking a different tack on what to do with it.  Factory test doesn't do a full render, so the dynamic template render of Add versus Update cannot be tested as both render as empty string in result.   Client test will do the render and allow the test of result content.

## Location within the Book

* Chapter or Appendix: 56
* Section:  2 (Add) and 3 (Update)
* Subsection: 

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 
``` python
def test_cheese_create_correct_title(rf, admin_user):
    """Page title for CheeseCreateView should be Add Cheese."""
    request = rf.get(reverse('cheeses:add'))
    request.user = admin_user
    response = CheeseCreateView.as_view()(request)
    assertContains(response, 'Add Cheese')
```

## Possible Solutions

``` python
from django.test import Client

def test_cheese_create_correct_title(rf, admin_user):
    """Page title for CheeseCreateView should be Add Cheese."""
    url = reverse('cheeses:add')
    c=Client()
    c.force_login(admin_user)       # need to be a logged in user to add cheeses
    response = c.get(url)           # response 'resolver_match': 
    # ResolverMatch(func=everycheese.cheeses.views.CheeseCreateView, args=(), kwargs={},
    #  url_name=add, app_names=['cheeses'], namespaces=['cheeses'], route=cheeses/add/
    assertContains(response, 'Add Cheese')  # passes - template renders
```

similar for update:

```
def test_client_good_cheese_update_view(rf, admin_user, cheese):
    c = Client()
    # Add an authenticated user
    c.force_login(admin_user)
    kwargs = {'slug': cheese.slug}
    url = reverse("cheeses:update", kwargs=kwargs)
    # get the response 
    response = c.get(url, kwargs=kwargs)
    # Test that the response is valid
    assertContains(response, "Update Cheese")
```

**Comment by kevin-j-murray** [comment]
side note followed the course on a windows laptop, and error from running test from my environment appears as:

???????????????????????????????????????????????? test_factory_cheese_create_correct_title ?????????????????????????????????????????????????

rf = <django.test.client.RequestFactory object at 0x00000000076E9850>, admin_user = <User: admin>

    def test_factory_cheese_create_correct_title(rf, admin_user):
        """Page title for CheeseCreateView should be Add Cheese."""
        request = rf.get(reverse('cheeses:add'))
        request.user = admin_user
        callable_obj = CheeseCreateView.as_view()
        response = callable_obj(request)        # response 'resolver_match': None
>       assertContains(response, 'Add Cheese')  # fails - no action rendered -> get ' Cheese'

everycheese\cheeses\tests\test_views.py:95:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\programdata\miniconda3\envs\everycheese\lib\site-packages\pytest_django\asserts.py:18: in assertion_func
    return func(*args, **kwargs)
c:\programdata\miniconda3\envs\everycheese\lib\site-packages\django\test\testcases.py:454: in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <django.test.testcases.TestCase testMethod=run>, expr = False, msg = "False is not true : Couldn't find 'Add Cheese' in response"

    def assertTrue(self, expr, msg=None):
        """Check that the expression is true."""
        if not expr:
            msg = self._formatMessage(msg, "%s is not true" % safe_repr(expr))
>           raise self.failureException(msg)
E           AssertionError: False is not true : Couldn't find 'Add Cheese' in response

c:\programdata\miniconda3\envs\everycheese\lib\unittest\case.py:765: AssertionError

**Comment by kevin-j-murray** [comment]
One last note, give credit where credit is due - sources I read before arriving at the above 

https://stackoverflow.com/questions/30992377/django-test-requestfactory-vs-client
RequestFactory and Client have some very different use-cases. To put it in a single sentence: RequestFactory returns a request, while Client returns a response.

and

https://docs.djangoproject.com/en/3.0/topics/testing/tools/#the-test-client

**Comment by pydanny** [comment]
Wow, this is an epic issue. Thanks for posting it! Digging in!

**Comment by pydanny** [comment]
🚢 🧀 

I like your approach, but there's a simpler way. Which is to introduce code at the view and template level that doesn't require digging into fancier test code. 

That said, I love doing fancy things with `resolver_match` and your test samples will prove useful in future extensions. 😄

**Comment by kevin-j-murray** [comment]
Thank you.  Look forward to the updated editions of the book, keeps getting
better each time.

    One of the add on spin offs could be a way to go production with new
Django application that you like.  Sure that there are many options on
such, but do like your work.

Many thanks,
Kevin Murray

**Comment by pydanny** [comment]
You've been given attribution in the next edition of the book!
