### ISSUE TITLE
46.6 Implement Get_absolute_url() | VS get_success_url() on the view

### ISSUE THREAD

**Issue by bfmcneill** [roygreenfeld/django-crash-course#185]
## Location within the Book

* Chapter or Appendix: 46
* Section: 6
* Subsection:

## Description 

get_absolute_url()  on the model V.S. get_success_url() on the class based view

## Possible Solutions

Make a cheese tip "Something You Should Know" box that explains which method is superior and any intuition we can borrow from you on when to use one vs the other

**Comment by pydanny** [comment]
We've decided this is a little tangential for the core tutorial and better handled in a future extension which goes more indepth with views. Or even might deserve a place in Two Scoops of Django 3.x,.
