### ISSUE TITLE
URL route triggers unnecessary warning

### ISSUE THREAD

**Issue by jjrugui** [roygreenfeld/django-crash-course#186]
## Location within the Book

* Chapter or Appendix: 46
* Section: 2
* Subsection:

## Description 
In `cheeses/urls.py` referenced during this section the route for the list view has an additional '/' that was not present in previous reference. This triggers the following warning when running the server:

```
WARNINGS:
?: (urls.W002) Your URL pattern '/' [name='list'] has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
```

## Possible Solutions
Not a big problem but this warning can be omitted by keeping the route as in the previous reference to `cheeses/urls.py`

**Comment by pydanny** [comment]
🚢 🧀
