### ISSUE TITLE
Typo fix or rephrasing

### ISSUE THREAD

**Issue by jjrugui** [roygreenfeld/django-crash-course#187]
## Location within the Book

* Chapter or Appendix: 49
* Section: 1
* Subsection: 1

## Description 
I am not sure about if it's me or a typo but the text in the first paragraph of this section is a bit confusing, specially the following sentence.

> Selections cannot for rows not in the second table

**Comment by pydanny** [comment]
We just corrected this, thank you for submitting it! We will be giving attribution in the next update of the book. 😄 

🚢 🧀

**Comment by pydanny** [comment]
Hey @jjrugui, we want to give you attribution in the book, but we need a name for you. Please let us know here what name you want to be listed under.

**Comment by jjrugui** [comment]
Hey @pydanny I just updated my profile with my name in case you want to get it. Thank you very much!

I'm currently going through the book so I hope I can help you spotting small mistakes :)
