### ISSUE TITLE
25.2: Number of Tests Typo

### ISSUE THREAD

**Issue by realcooltrev** [roygreenfeld/django-crash-course#188]
## Location within the Book

* Chapter or Appendix: 25
* Section: 2
* Subsection: 0
* Page: 125

## Description 

The included image for this section (and the actual results from running `coverage run -m pytest`) shows that 9 tests were run and passed, but the wording in the following text states that 8 tests were run:

>2. Django ran **8** tests in 1.94 seconds, then reported 'OK'.

>If any of those **8** tests had failed, Django would have reported the failures to us via error messages.

## Possible Solutions

The mentions of 8 in the lines of text provided above should be changed to:

>2. Django ran **9** tests in 1.94 seconds, then reported 'OK'.

>If any of those **9** tests had failed, Django would have reported the failures to us via error messages.

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you for submitting it! We will be giving attribution in the next update of the book. :smile:
:ship: 🧀

**Comment by lefthand3r** [comment]
This was still in the most recent version I received on March 19th?

**Comment by lefthand3r** [comment]
@Scarletbegonias68 It still says 8 tests in the most current version I received (Mar 22, 2020)
