### ISSUE TITLE
self not defined

### ISSUE THREAD

**Issue by pqmertz** [roygreenfeld/django-crash-course#19]
As someone completely new to writing test...    Just trying to follow along.   So maybe is my mistake but...   I come with this for
28.3 
import pytest   
from ..models import Cheese

def test___str__(self):
    cheese = Cheese.objects.create(
        name="Stracchino",
        description="Semi-sweet cheese that goes well with starches.",
        firmness=Cheese.FIRMNESS_SOFT,
    )
    assert cheese.__str__() == "Stracchino"

coverage run -m pytest
E       fixture 'self' not found

**Comment by pydanny** [comment]
Well that's really embarrassing on our part, yet thanks for catching it! We'll correct that in tomorrow's update and give you attribution. In the meantime the correct test is:

``` python
def test___str__():
    cheese = Cheese.objects.create(
        name="Stracchino",
        description="Semi-sweet cheese that goes well with starches.",
        firmness=Cheese.FIRMNESS_SOFT,
    )
    assert cheese.__str__() == "Stracchino"
```

**Comment by pqmertz** [comment]
I had tried that earlier that gives:
RuntimeError: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.

So I added this like in the users test_models.py 
pytestmark = pytest.mark.django_db

Even though I have no idea what it means

**Comment by pqmertz** [comment]
Just a reminder to address 41.5 & 41.6 as well.

**Comment by pydanny** [comment]
@pqmertz Wow! This is an awesome issue. Thank you for catching it! Some explanation:

`pytestmark = pytest.mark.django_db` is a pytest monkeypatch that connects tests on a module to the test database. Without it, our tests can't find the database, hence the error you received that said:

```
RuntimeError: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```
