### ISSUE TITLE
10 No explanation on View classes

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#190]
## Location within the Book

* Chapter or Appendix: 10 Add a Simple Homepage View
* Section:
* Subsection:

## Description 

> `HomepageView` subclassed `TemplateView`

TemplateView is used without any explanation.

## Possible Solutions

It should be explained that Django has a number of built-in views, including `TemplateView` (which renders a template), `RedirectView` (which redirects to a given URL), and, most importantly, `View`, the parent of all the other views, in which we can create any logic we might need.

**Comment by pydanny** [comment]
🚢 🧀
