### ISSUE TITLE
27.6.4 Incorrect grammar

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#192]
## Location within the Book

* Chapter or Appendix:
* Section:
* Subsection: 27.6.4 Add Firmness Field

## Description 

> For those with pre-3.0 Django experience, `models.TextChoices` and `models.IntegerChoices` is new feature of the framework. 

## Possible Solutions

is new feature => are new features

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you for submitting it! We will give attribution in the next update of the book. :smile:
:ship: :cheese:
