### ISSUE TITLE
Reference to missing resource

### ISSUE THREAD

**Issue by The-Judge** [roygreenfeld/django-crash-course#196]
#  Location within the Book

* Chapter: 18.6

## Description 

You list `test.txt` in the book, but that file does not exist in [GH](https://github.com/roygreenfeld/django-crash-starter/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements)

**Comment by pydanny** [comment]
Thanks @The-Judge! In the next update your name will show up in the acknowledgements chapter!

🚢 🧀
