### ISSUE TITLE
55.4.1: Template Content Block Tag Typo

### ISSUE THREAD

**Issue by realcooltrev** [roygreenfeld/django-crash-course#198]
## Location within the Book

* Chapter or Appendix: 55
* Section: 4
* Subsection: 1

## Description 

The included image for this section that shows how to fix the code in the cheese_form template for the content block tag, starting on page 264 and continuing to page 265.

However, the line at the bottom of this image is the line:

`{% endblock title %}`

The issue with this is that the title block tag is above this section and would already be closed. The block tag that is being closed is the content block tag, not the title block tag.

## Possible Solutions

This last line of code in the image that starts on page 264 and continues on page 265:

`{% endblock title %}`

should be changed to:

`{% endblock content %}`

**Comment by pydanny** [comment]
🚢 🧀 

We just added you to our acknowledgements chapter, you will show up in our next update. 🛩
