### ISSUE TITLE
Tech Reviewers Typo

### ISSUE THREAD

**Issue by GarretL** [roygreenfeld/django-crash-course#199]
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Chapter or Appendix: Part III Aftermatter
* Section: 60 Acknowledgement
* Subsection: 60.1 Tech Reviewers

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

>  The book would not be in the shape it is without the two following people:

Then three people are listed.

**Comment by Scarletbegonias68** [comment]
We just corrected this, thank you, Garrett, for submitting it! We will be giving attribution in the next update of the book. :smile:

:ship: :cheese:
