### ISSUE TITLE
Set Up a New Conda Environment.

### ISSUE THREAD

**Issue by obinnaeye** [roygreenfeld/django-crash-course#2]
This is not a serious issue, but considering how the book has simplified every step, I just want to point this out. 

When you `conda create -n hellodjango python=3.8` (as stated in page 7 of the pdf book), there is a step that says 
`The following NEW packages will be INSTALLED:`
`bla bla bla`

`Proceed ([y]/n)?`

The default response should be `y` followed by pressing the enter key.

Also, the virtual env is not activated automatically, you are asked to run `conda activate hellodjango` to get it activated.

**Comment by pydanny** [comment]
Thanks for spotting that for us! Acknowledgment documented, you'll see your name in the book after the next update!

🚢 🧀
