### ISSUE TITLE
Faker issues on page and factories.py

### ISSUE THREAD

**Issue by pqmertz** [roygreenfeld/django-crash-course#20]
39.2    Given the formatting on the page not sure about this line...  but can't seem to figure out how to edit it to get it to work either.
description = factory.Faker('paragraph', nb_sentences=3, variable

Does this need to be imported?
from faker import Faker
fake = Faker()

I can't find this method either.   Should the line be 
fake.text()

oh and I believe 
firmness = factory.fuzzy.FuzzyChoice([x[0] for x in Cheese.FIRMNESS])
should be
Cheese.FIRMNESS_CHOICES

**Comment by pydanny** [comment]
I clarified this in the book and fixed the line length issue that truncated `Cheese.FIRMNESS_CHOICES`.
