### ISSUE TITLE
ForeignKey requires an on_delete 

### ISSUE THREAD

**Issue by pqmertz** [roygreenfeld/django-crash-course#27]
48.1
creator = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)

TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by pydanny** [comment]
Thanks for the submission!

🚢 🧀

**Comment by DROMZEE** [comment]
48.1

a solution

`creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)`

source : https://stackoverflow.com/questions/44026548/getting-typeerror-init-missing-1-required-positional-argument-on-delete
