### ISSUE TITLE
Clarification for Conda installation on mac

### ISSUE THREAD

**Issue by ivange94** [roygreenfeld/django-crash-course#32]
## Introduction

* Introduction
* Installing Conda on Mac:

## Description 

After installing conda using the package installer from the website. `conda list` kept giving me command not found.

I'm on macOS Mojave. To fix this I had to add 

`eval "$(/opt/miniconda3/bin/conda shell.zsh hook)"` to my `.zshrc` file. Though this makes conda work, I'm not certain of the other implications it causes as whenever I start my terminal it looks like an environment is activated as seen on the screenshot below 

<img width="1680" alt="Screen Shot 2020-02-09 at 19 57 57" src="https://user-images.githubusercontent.com/11330494/74108074-9a968000-4b76-11ea-94ca-b3d2026e5600.png">

If you look at the top right, you'll see a `miniconda3`. I've customised my terminal to always show an activated environment like that so I'm not sure if the command I added to my path always activates an environment but that solution seems to be the recommended solution by developers of Anaconda as explained in this blog post https://towardsdatascience.com/how-to-successfully-install-anaconda-on-a-mac-and-actually-get-it-to-work-53ce18025f97

**Comment by pydanny** [comment]
@ivange94 Thanks for the detailed answer! In the text I'm going to link directly to the article you mention, as that provides in-depth guidance our readers can use. 

You are getting attribution for this contribution 😄 

🚢 🧀
