### ISSUE TITLE
Grammar/Awkward Wording - 11.3

### ISSUE THREAD

**Issue by diek** [roygreenfeld/django-crash-course#35]
## Location within the Book

* Chapter or Appendix:11
* Section:3
* Subsection:

## Description 

> If grammar, enter problematic text here, otherwise delete this line.
The word "context" with the code is not making sense, and the sentence has no clear end.

**Comment by kanusek** [comment]
I just posted the same issue, I'll delete mine. 
Also in section 11.3 we assign 
`context['my_statement'] = 'Nice to see you!'`
In the paragraph following it is referenced as 'hello'
> You assigned it the value of hello.

**Comment by pydanny** [comment]
Thanks @diek and @kanusek! 

🚢 🧀

**Comment by pydanny** [comment]
@kanusek, we're granting you attribution! Thanks for the catch!
