### ISSUE TITLE
Section 2.3 console output listing margin issue

### ISSUE THREAD

**Issue by itsromack** [roygreenfeld/django-crash-course#36]
## Location within the Book

* Chapter:2
* Section:3

## Description 

> Console output listing overlaps the projected margin.

<img width="725" alt="Screenshot 2020-02-11 at 2 38 25 PM" src="https://user-images.githubusercontent.com/357637/74215679-ce8bb580-4cdc-11ea-866a-f80d163fd6c6.png">

**Comment by pydanny** [comment]
🚢 🧀
