### ISSUE TITLE
Section 3.2 code listing margin issue

### ISSUE THREAD

**Issue by itsromack** [roygreenfeld/django-crash-course#37]
## Location within the Book

* Chapter:3
* Section:2

## Description 

> Code listing overlaps the projected margin. Should the code's font be reduced or reduce some indentation spaces. You know what to do.

<img width="744" alt="Screenshot 2020-02-11 at 2 44 42 PM" src="https://user-images.githubusercontent.com/357637/74215802-507bde80-4cdd-11ea-83f0-5ea25909973d.png">

**Comment by pydanny** [comment]
🚢 🧀

**Comment by itsromack** [comment]
awesome!
