### ISSUE TITLE
Suggestion - 3.1 new Visual Studio Code project

### ISSUE THREAD

**Issue by jtalarovich** [roygreenfeld/django-crash-course#39]
In 3.1, after a fresh install of Visual Studio Code the command 'code hellodjango' didn't work until I installed the shell command.  https://code.visualstudio.com/docs/setup/mac

Mac OS 10.15.3

**Comment by pydanny** [comment]
Thanks @jtalarovich! We're giving you attribution now!

🧀 🚢

**Comment by pydanny** [comment]
Can you supply us with your full name so we can attribute you correctly? Or you can just use your GitHub name - it's up to you.

**Comment by jtalarovich** [comment]
Joe Talarovich

Just wanted to say, I’m having a blast with this book!  I made it to section 17 today at work and having so much fun I’m planning on having a late night tonight and work from home tomorrow to keep pushing through!

I’m the CTO at the company I work for so I don’t code nearly as much as I used to, but about 2 years ago I made the decision to take ColdFusion out of our stack and replace it with Django. (I was a DoD ColdFusion dev for over 15 years, but always wrote python as well on the side)  I never learned Django at the time but got my lead programmer to learn it.  He found and used your Two Scoops book and with that foundation built multiple apps for the company!  He found that you had this new book so we jumped on it… and I decided to go through it with him so I can help out more with our new code base.

You’re teaching style is amazing!!!  Thanks so much!!!!

Thanks!
Joe Talarovich
CTO
7501 Boulder View Drive, Suite 601
Richmond, VA 23225
www.goodneighbor.care <https://www.goodneighbor.care/>

This email message is intended only for the use of the addressee and may contain information that is privileged, confidential and exempt from disclosure under applicable law.  IF YOU ARE NOT THE INTENDED RECIPIENT, PLEASE CONTACT THE SENDER BY REPLY EMAIL AND DESTROY ALL COPIES OF THE ORIGINAL MESSAGE.  THANK YOU.

**Comment by jtalarovich** [comment]
> Can you supply us with your full name so we can attribute you correctly? Or you can just use your GitHub name - it's up to you.

Joe Talarovich

**Comment by SmartC2016** [comment]
@jtalarovich Thank you - with your help I could get it fixed as well.
