### ISSUE TITLE
Section 11.3 - Mismatch between value in code and in the text

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#43]
Chapter or Appendix: 11
    Section: 3
    Subsection: the last two paragraphs

## Description 

Mismatch between value in code and what is stated as value in the last two paragraphs.

```
context['my_statement'] = 'Nice to see you!'
```

In the second last chapter is says: "You assigned the value _hello_." But isn't the value 'Nice to see you!' ???

Also in the last chapter ... "... and _hello_ is its corresponding value". Shouldn't this be "Nice to see you!" as well?

**Comment by SmartC2016** [comment]
50% is solved. :) The last paragraph is in today's version ok. The second last chapter still says: „There, you defined a context variable called my_statement. You assigned it the value of **_hello_**.“

Proposal: You assigned it the value of **_Nice to see you!_**

**Comment by pydanny** [comment]
@SmartC2016 Can you provide your full same so we can attribute you accurately?

**Comment by SmartC2016** [comment]
Christian Hetmann - Thank you.
