### ISSUE TITLE
Suggestion: step 4 installing postgres

### ISSUE THREAD

**Issue by jtalarovich** [roygreenfeld/django-crash-course#44]
I downloaded a fresh install of Postgres from https://postgresapp.com/downloads.html.  Then later on when I was ready to do my first 'createdb' it didn't work because i didn't have the command in my path.  I went back to the site and found what i needed to run to get the CLI tools working.  https://postgresapp.com/documentation/cli-tools.html

sudo mkdir -p /etc/paths.d &&
echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp

Mac OSX 10.15.3

**Comment by pydanny** [comment]
Thanks for spotting this @jtalarovich. It will show up in the next update and you'll be listed in the acknowledgements.

🧀 🚢
