### ISSUE TITLE
Typo under heading “A Professional-Quality Development Environment”  

### ISSUE THREAD

**Issue by moluwole** [roygreenfeld/django-crash-course#5]
“Have a computer with at least a *gigabyle* (1 GB) of harddrive space”

gigabyle should be gigabyte

**Comment by audreyr** [comment]
@moluwole Wow, good eye for detail with catching this typo!

@Scarletbegonias68 Hey Carla, want to try fixing this typo? Message me privately when you have a moment and I can walk you through the process of making the correction.

**Comment by pydanny** [comment]
I took care of this one but @Scarletbegonias68 can do the next one. 😄 

🚢 🧀
