### ISSUE TITLE
Provide tip for experienced people who don't want to use Conda

### ISSUE THREAD

**Issue by pydanny** [roygreenfeld/django-crash-course#50]
## Location within the Book

* Chapter or Appendix: Ultimate Django Setup 
* Section: Step 1: Install Conda 

## Description 

Experienced users sometimes want to use pyenv, virtualenv, poetry, docker, or whatever. Tell them they can use it if they want but that we use conda terminology throughout the book

**Comment by diek** [comment]
Good point, I was thinking the same thing
