### ISSUE TITLE
Section 21.9 - Code is not the same as in book

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#54]
## Location within the Book

* Chapter or Appendix: 21
* Section: 9
* Subsection: class UserUpdateView

## Description 

I'm not sure, if this is really an "Issue" but the code in the book in this section is not 100% as the code downloaded via cookiecutter.

The #comments which are in the book for example are missing in the code.
In the book ```fields```is defined at first, in the code it is ```model```.

Let me know if such "Issue" is too picky.

**Comment by pydanny** [comment]
No such thing as a "too picky" issue. Your oversight is making a huge difference in the quality of Django Crash Course. 😄 

🚢 🧀
