### ISSUE TITLE
Section 21.11 Hint where to find allauth's urls.py

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#55]
## Location within the Book

* Chapter or Appendix: 21
* Section: 11
* Subsection: towards the end of this paragraph

## Description 
I'm still somewhat a beginner although I made the one or the other Django tutorial. However, you describe the eMail-Button and the link to ``àccount_email```. It took me a while to find the allauth's urls.py in my system - where the ```site-packages```of the virtual environment.

Maybe a hint for the readers where they can find it in their system could be helpful here. Just an idea.

Thank you.

BTW, you referenced the urls.py on GitHub and selected Line 17. The ```account_email``` is in Line 16.

**Comment by pydanny** [comment]
Hey @SmartC2016, we clarified the location in the link to the `allauth` source code. 

As for `allauth` on your system's `site-packages` directory, it's good that you introspected enough to find that. Just remember the code in site-packages is ephemeral, don't ever make changes directly in there. 😄 

🧀 🚢
