### ISSUE TITLE
Error installing requirements, unable to start runserver

### ISSUE THREAD

**Issue by BobEarlK** [roygreenfeld/django-crash-course#56]
* Chapter or Appendix: 17
* Section:17.6 Install the dependencies
* Subsection:

## Description 

after:  pip install -r requirements/local.txt

some errors with install including:  
Building wheel for rcssmin (setup.py) ... error
  ERROR: Command errored out with exit status 1:
...
  error: command 'gcc' failed with exit status 69
  ----------------------------------------
  ERROR: Failed building wheel for regex

then, after:  python manage.py migrate

No module named 'compressor'

...and unable to start runserver

**Comment by BobEarlK** [comment]
I think I may have found the problem:  when installing requirements, compressor wouldn't install due to first needing to agree to Xcode/iOS license.  typing:  
sudo xcodebuild -license

agreeing to the license, and then:

pip install -r requirements/local.txt

fixed the issue

**Comment by pydanny** [comment]
Thanks! I've given you attribution for this awesome contribution. You will see the results in the next update to the book. 😄 

🚢 🧀
