### ISSUE TITLE
Section 24.2 - Number of tests stated wrong

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#57]
## Location within the Book

* Chapter or Appendix: 24
* Section: 2
* Subsection: step-by-step - Step 2

## Description 

It says "Django ran 7 tests in 0.445 seconds ...". In the picture above it stated "8 passed" and also in the paragraph below it says "If any of the 8 tests ...". 

And when you run the code, it is really 8 tests.

One small thing: In the picture it says the tests ran for 1.94s and in the text in step 2 it says 0.445 seconds. When you run the tests a second or a third time, the tests run a lot faster. I guess that is where the different times come from.

**Comment by pydanny** [comment]
🧀 🚢
