### ISSUE TITLE
Section 24.3 - There is no TestUser class

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#58]
## Location within the Book

* Chapter or Appendix: 24
* Section: 3
* Subsection:

## Description 

I might be totally wrong with this one, as I would still consider myself as a beginner, but the file referenced in the first paragraph ```everycheese > users > tests > test_models.py```does not contain any class and there is only one function.

The code segment in this Section in the book is the same, as I have downloaded - no class.

The text doesn't seem to fit to the code.

**Comment by pydanny** [comment]
That's a relic of our corporate training, which used UnitTest until a couple years ago when we switched to pytest. Thanks for the catch!

🚢 🧀
