### ISSUE TITLE
Section 27.4 - I have a different output for "cheese"

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#60]
## Location within the Book

* Chapter or Appendix: 27
* Section: 4
* Subsection: code segment [2] and [3]

## Description 

I run on python 3.7.6 and Django 3.0.2 - I'm not sure, if this makes the difference.

When I type in shell_plus:

```cheese``` I get ```<Cheese: Cheese object (1)>``` vs. in the book ```<Cheese: Cheese object>```

When I type ```print(cheese)``` I get ```Cheese object (1)``` vs. in the book ```Cheese object```

**Comment by pydanny** [comment]
I can't duplicate this issue. Anyone else able to duplicate this?

**Comment by pydanny** [comment]
Since we can't duplicate the issue, we're going to close it for now. If we can duplicate it we'll reopen this issue.
