### ISSUE TITLE
Section 28.3 AttributeError: type object 'Cheese' has no attribute 'FIRMNESS_SOFT'

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#61]
## Location within the Book

* Chapter or Appendix: 28
* Section: 3
* Subsection: the code of the test function

## Description 
Same as previously in 27.3

In the book it says:
```firmness=Cheese.FIRMNESS_SOFT```

this will cause the test to fail with ```AttributeError: type object 'Cheese' has no attribute 'FIRMNESS_SOFT'```

should say:
```firmness=Cheese.Firmness.SOFT```

**Comment by pydanny** [comment]
🧀 🚢 

Fixed it in the other chapters too.
