### ISSUE TITLE
Introduction: wrong Django version

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#62]
## Location within the Book

* Chapter or Appendix: Introduction
* Section: This Book is intended for Django 3.3 and Python 3.8
* Subsection:

## Description 

> This Book is intended for Django 3.3 and Python 3.8

Unless you came back from the future, the version in the section name should be Django 3.x  :-)

**Comment by pydanny** [comment]
Thanks @quique! We'll give you attribution in the next update of the book!

🚢 🧀
