### ISSUE TITLE
Suggested instructions for Linux

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#65]
## Location within the Book

* Chapter or Appendix: The Ultimate Django Setup
* Section: Step 1: Install Conda
* Subsection:

## Description 

In case you are interested, here are the instructions for installing Conda on Linux:

1. Go to <https://docs.conda.io/en/latest/miniconda.html#linux-installers>
2. Find the Python 3.7 versions.
3. Click the link with 64-bit in the name and download.
4. On the computer, open a terminal.
   Go to the directory where you saved the file: `cd ~/Downloads`
   Make the file executable: `chmod a+x Miniconda3-latest-Linux-x86_64.sh`
   Execute the file: `./Miniconda3-latest-Linux-x86_64.sh`.
5. Follow the instructions on the screen. If unsure about any setting, accept the defaults. We can change them later.
6. When installation is finished, close the current terminal window and open a new one.
7. Type `conda list` and press enter.

Upon request, I could also provide instructions for installing VSCode, Git and PosgreSQL on Linux.

**Comment by pydanny** [comment]
Wow, @quique, we don't know what to say. We're going to include this near verbatim. 

For reference, Django Crash Course is written in R-Markdown, so porting your text over is very easy for us.

**Comment by pydanny** [comment]
Yes, instructions for the other tools would bring us a lot of joy. 🐧
