### ISSUE TITLE
Internal reference not working

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#67]
## Location within the Book

* Chapter or Appendix: 1 Hello, World in Django
* Section: 1.4 Prerequisites
* Subsection:

## Description 

>  If we don’t have it ready, go to the [Ultimate Django Setup] chapter.

I guess this should be an internal link, but at least in the PDF, it's not working.
Probably an error in the LaTeX markup.

**Comment by pydanny** [comment]
🧀 🚢
