### ISSUE TITLE
8.3.2: Typo in Spanish word

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#70]
## Location within the Book

* Chapter or Appendix: 8 Prepping the Project for Templates
* Section: 8.3 Lists? Dictionaries?
* Subsection: 8.3.2 What’s a Python Dictionary?

## Description 

```
{'vanilla': 'vanilla', 'chocolate mint': 'choco menta', 'coffee': 'café'}
```

The Spanish term is _vainilla_.

**Comment by pydanny** [comment]
Mi espanol es malo.

🚢 🧀

**Comment by quique** [comment]
Siempre puedes aprender más  :-)
