### ISSUE TITLE
14: Missing comma

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#74]
## Location within the Book

* Chapter or Appendix: 14 The EveryCheese Project
* Section:
* Subsection:

## Description 

> We’re your friendly hosts, Daniel and Audrey and we love cheese.

I think there should be a comma after Audrey:

_We’re your friendly hosts, Daniel and Audrey, and we love cheese._

**Comment by pydanny** [comment]
🚢 🧀
