### ISSUE TITLE
15.5.2: Missing period at the end of sentence

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#75]
## Location within the Book

* Chapter or Appendix: 15 Using Cookiecutter and Template
* Section: 15.5 Tips and Troubleshooting
* Subsection: 15.5.2 Unfamiliar Options

## Description 

>  django-crash-starter listed above, go with the defaults for that option. (It may change after the printing of this book! We’ll try not to change it too much)

There should be a full stop at the end.

**Comment by pydanny** [comment]
🚢 🧀
