### ISSUE TITLE
14.3 The newly created env should be activated

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#77]
## Location within the Book

* Chapter or Appendix: 14 The EveryCheese Project
* Section: 14.3 Create a New Virtual Environment
* Subsection:

## Description 

> Create **and activate** a new Conda environment called everycheese:
> ```
> conda create -n everycheese python=3.8
> ```

This code creates the `everycheese` project, but it doesn't activate it.

We should also run 
```
conda activate everycheese
```
After that, our command-line should look like something like:
```
(everycheese) $
```

Failing to activating the `everycheese` enviroment, will cause the following commands (installing cookiecutter) to be executed on the `hellodjango` environment.

**Comment by pydanny** [comment]
Wow, thanks for not just a correction but a full-fledged suggestion! 😄 

🚢 🧀
