### ISSUE TITLE
Section 35.4: Difference in html / code vs. book

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#79]
## Location within the Book

* Chapter or Appendix: 35
* Section: 4
* Subsection: code for the navbar

## Description 

There are two differences in the navbar code of the base.html in the book vs. in the code.

In the code it says:
```
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)/span></a>
     </li>
```

In the book it says:
```
<ul class="nav navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'home' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'about' %}">About</a>
  </li>
</ul>
```

So, the ```ul``` has an additional class in the code: ```mr-auto```
And the ```home``` has another ```span``` element.

**Comment by pydanny** [comment]
Thanks @SmartC2016! For reference, the `sr-` items are for screen readers used by the visually disadvantaged. We've fixed the book to make the code. 😄 

🧀 🚢
