### ISSUE TITLE
Path for home page p55

### ISSUE THREAD

**Issue by pmuston** [roygreenfeld/django-crash-course#8]
Got msg
Using the URLconf defined in hellodjango.urls, Django tried these URL patterns, in this order:
admin/
/ [name='home']
The empty path didn't match any of these.

should be:
path('', HomepageView.as_view(), name='home'),

**Comment by pydanny** [comment]
Old regex habits die hard! When we tested it, we corrected it without thinking. We'll pay more attention to that in the future! 😄 

🚢 🧀
