### ISSUE TITLE
Section 35.4: Typo - Missing '

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#80]
## Location within the Book

* Chapter or Appendix: 35
* Section: 4
* Subsection:

## Description 

There is an apostrophe missing.

In the book it says:
„Instead, {% url 'cheeses:list' %} would automagically link to `127.0.0.1:8000/les-fromages/.“

At the very end there is an apostrophe missing.

Proposal:
„Instead, {% url 'cheeses:list' %} would automagically link to `127.0.0.1:8000/les-fromages/´.“

**Comment by pydanny** [comment]
🚢 🧀
