### ISSUE TITLE
17.5.1: Explain how to quit psql

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#81]
## Location within the Book

* Chapter or Appendix:
* Section:
* Subsection: 17.5.1 Troubleshooting PostgreSQL: Role Does Not Exist

## Description 

```
psql -U postgres
postgres=# CREATE ROLE audreyr WITH CREATEDB LOGIN;
```

Many readers won't know how to quit `psql`.
I suggest adding this line:
```
postgres=# \q
```

**Comment by pydanny** [comment]
🚢 🧀
