### ISSUE TITLE
19.3: Incorrect button text

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#82]
## Location within the Book

* Chapter or Appendix:
* Section: 19.3 Create the GitHub Project
* Subsection:

## Description 

> Click the _Create project_ button.

As Figure 8 shows, it actually is the _Create repository_ button.

Also, and probably nitpicking, in Figure 8 the _Public_ radio button is selected, when it should be the _Private_ radio button.

**Comment by pydanny** [comment]
None of this is nitpicking. Accuracy is very important in any book.:smile:

🚢 🧀
