### ISSUE TITLE
Section 21.3: Rendering issue on PDF

### ISSUE THREAD

**Issue by omaciel** [roygreenfeld/django-crash-course#83]
## Location within the Book

* Chapter or Appendix: 21
* Section: 3
* Subsection:

## Description 

The screenshot below shows that the following message is rendered off the screen when viewing the PDF version of the book on a Mac OS Preview app. I suspect that it may be related to a single quote in the text?

```
EMAIL_BACKEND = env(
    "DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBack
```

<img width="1050" alt="Screen Shot 2020-02-15 at 5 54 45 PM" src="https://user-images.githubusercontent.com/53362/74596366-4844db80-501c-11ea-9852-8cb8bfc076df.png">

**Comment by pydanny** [comment]
🚢 🧀
