### ISSUE TITLE
Section 22.4: Move figures 17 and 18 to their respective places

### ISSUE THREAD

**Issue by omaciel** [roygreenfeld/django-crash-course#84]
## Location within the Book

* Chapter or Appendix: 22
* Section: 4
* Subsection:

## Description 

Please note that the following paragraphs end the sentence stating that the reader should be able to see the expected output from changing the **UserUpdateView** and **UserDetailsView** views:

> Click on the My Info button again. You should see your new bio
field:

and 

> As you can see, now users can add and edit their bios. But the bios still don't show up on user profiles. You’ll notice that UserDetailView still looks like this:

Furthermore, this last paragraph could perhaps be improved as shown below (suggested changes highlighted in bold)

```diff
-As you can see, now users can add and edit their bios. But the bios still don't show up on user profiles. You’ll notice that UserDetailView still looks like this:
+As you can see, now users can add and edit their bios. But the bios **field** still **doesn't** show up on user profiles. You’ll notice that UserDetailView still looks like this:
```

Since the figures mentioned by these two paragraphs are found later in this chapter, you could either move them up to align directly underneath the paragraphs OR change the paragraphs to include `as shown by Figure XX`, where XX is the corresponding number of the figure.

<img width="1050" alt="Screen Shot 2020-02-15 at 6 11 06 PM" src="https://user-images.githubusercontent.com/53362/74596639-eb4b2480-501f-11ea-8a58-e460461311e8.png">

**Comment by pydanny** [comment]
Well, you just identified a bug in our PDF rendering process. The images are specified in the right location, they just aren't going into the right places in the text. I've heard this can happen with XaLaTeX, I've just not seen it yet. For reference, here is the Markdown dialogue (after your dialogue suggestions):

``` markdown
As you can see, now users can add and edit their bios. But the bios **field** still **doesn't** show up on user profiles. You’ll notice that UserDetailView still looks like this:

![UserDetailView Without Bio](images/userdetailview.png)
```

We can force page breaks and that should fix it. However, it won't be elegant. We'll do that for now and aim for a better solution later.

**Comment by omaciel** [comment]
Once a quality engineer, always a quality engineer :) Thanks for the update. :)

**Comment by pydanny** [comment]
Argh. It rendered okay on my laptop, but incorrectly in our docker system for today's first beta release. 🤦‍♂ 

Today Xelatex is not my friend. 😩

**Comment by pydanny** [comment]
Okay, fixed it! Yay!

🚢 🧀
