### ISSUE TITLE
Section 23.1: Move figure 19 to its respective place

### ISSUE THREAD

**Issue by omaciel** [roygreenfeld/django-crash-course#85]
## Location within the Book

* Chapter or Appendix: 23
* Section: 1
* Subsection:

## Description 

As shown by the screenshot below, **Figure 19** should be moved to align directly below the following sentence:

> Go back to your profile page in the browser. Reload it if neces- sary. You should now see your bio:

Furthermore, I wonder if the word **necessary** should be split and not just *pushed down* the line?

<img width="1050" alt="Screen Shot 2020-02-15 at 6 29 43 PM" src="https://user-images.githubusercontent.com/53362/74596723-374a9900-5021-11ea-963c-50f5b4413998.png">

**Comment by pydanny** [comment]
🚢 🧀
