### ISSUE TITLE
Section 23.2: Move figure 22 to its respective place

### ISSUE THREAD

**Issue by omaciel** [roygreenfeld/django-crash-course#86]
## Location within the Book

* Chapter or Appendix: 23
* Section: 2
* Subsection:

## Description 

As shown by the screenshot below, **Figure 22** should be moved to align directly below the following sentence:

> Now when you reload your profile page in the browser, you should see that the line breaks are displayed properly:

<img width="1050" alt="Screen Shot 2020-02-15 at 6 33 02 PM" src="https://user-images.githubusercontent.com/53362/74596773-dbccdb00-5021-11ea-82c9-727b84f72bbb.png">

I'm not sure what to do with **Figure 20** and **Figure 21** though.

**Comment by pydanny** [comment]
🚢 🧀
