### ISSUE TITLE
UserUpdateView rendered incorrectly from cookiecutter

### ISSUE THREAD

**Issue by diek** [roygreenfeld/django-crash-course#87]
## Location within the Book

* Chapter or Appendix:17
* Section:7
* Subsection:

## The view UserUpdateView, rendered incorrectly. When I migrated everycheese I got an error
```
# Error
"/Users/derrick/workspace/django_stuff/everycheese/everycheese/users/views.py", line 22
    UpdateView):

# The view rendered as:
class UserUpdateView(LoginRequiredMixin 
UpdateView):
```

**Comment by quique** [comment]
Merging this pull request would fix this issue:
https://github.com/roygreenfeld/django-crash-starter/pull/8

**Comment by pydanny** [comment]
Ugh, sorry that was bad.

🚢 🧀
