### ISSUE TITLE
Section 41.5: Error in test code

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#91]
## Location within the Book

* Chapter or Appendix: 41
* Section: 5
* Subsection: test code

## Description 

The test code does not work. I guess it's the same relic from previous test class.
As there is no ```test class```, ```self.assertEqual``` cannot work.

Proposal (same as in 28.3):

```assert cheese.__str__() == "Stracchino"```

**Comment by pydanny** [comment]
🚢 🧀
