### ISSUE TITLE
Section 43.7.1 - Using double quotes instead of single quotes and one more

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#94]
## Location within the Book

* Chapter or Appendix: 43
* Section: 7
* Subsection: 1

## Description 

For all other imports of third party apps, double quotes have been used.

Book:

```
THIRD_PARTY_APPS = (
    ...
    'django_countries', # CountryField
)
```

Proposal:

```
THIRD_PARTY_APPS = (
    ...
    "django_countries", # CountryField
)
```

And, there is a "whitespace" missing:

Book:
„Add django_countries to settings/base.py’s THIRD_PARTY_APPSsetting:“

Proposal:
„Add django_countries to settings/base.py’s THIRD_PARTY_APPS setting:“

**Comment by quique** [comment]
This is controversial.
In Python, single-quoted strings and double-quoted strings are the same.

PEP8 does **not** make a recommendation for this. 

The Black code style prefers double quotes over single quotes:
<https://black.readthedocs.io/en/stable/the_black_code_style.html#strings>

Django coding style uses single quotes for strings:
<https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#python-style>

Personally, I don't care about what color the bikeshed is.

**Comment by SmartC2016** [comment]
Hey Enrique!

You are 100% correct.

I should have been clearer in my "issue" reporting. This "issue" is only about cosmetics.

The previously downloaded code looks like this:
```
THIRD_PARTY_APPS = [
    "crispy_forms",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
]
```

The the book tells to add this:
```
   'django_countries', # CountryField
```

I think within one list it is more consistent and more beautiful to just use either single quotes or double quotes.

But the code in the book is definetely not a mistake.

**Comment by pydanny** [comment]
You are both correct. 😄 

By nature I prefer single-quotes because on the US keyboard it's one less key-click. However, consistency is important - we don't want to through off beginners struggling with the absolute basics. 

I've gone ahead and moved this to double quotes.

**Comment by pydanny** [comment]
🚢 🧀
