### ISSUE TITLE
28.3: Explanation is lacking

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#97]
## Location within the Book

* Chapter or Appendix:
* Section: 28.3 Let’s Test the __str__() Method.
* Subsection:

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> Before we can write a test for this, we need to import a TestCase
> utility class and subclass it for testing the Cheese model. Start
> off cheeses/tests/test_models.py with this:
> ```
> import pytest
> 
> # Connects our tests with our database
> pytestmark = pytest.mark.django_db
> ```

I fail to see how you go from the explanation to the code below it.
TestCase is not imported nor subclassed   :-?

**Comment by pydanny** [comment]
Whoops! Fixed!

🚢 🧀
