### ISSUE TITLE
Redundant git option

### ISSUE THREAD

**Issue by quique** [roygreenfeld/django-crash-course#98]
## Location within the Book

* Chapter or Appendix:
* Section: 27.8 Commit Your Work
* Subsection:

## Description 

> Check which files have changed, then add them to a commit.
> ```
> git status
> git add everycheese/cheeses/
> git add config/settings/base.py
> ```
> Commit the changes and push:
> ```
> git commit -am "Add cheeses app"
> ```

As files were already added in the first chunk of code, the `-a` option in the commit command is redundant.
Alternatively, the `git add` commands could be removed.

```

**Comment by pydanny** [comment]
🚢 🧀
