### ISSUE TITLE
9.2: No explanation about .as_view() 

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#99]
## Location within the Book

* Chapter or Appendix: 9 Add a Simple Homepage View
* Section: 9.2 Add a URL Pattern for the Homepage
* Subsection:

## Description 

One of the bullets in the section mentioned above says `Route it to HomepageView.as_view()`. It would be great if there was a note about what `.as_view()` does and how we can use it effectively.

**Comment by pydanny** [comment]
🚢 🧀
